### ISSUE TITLE
Remove the line "I'm a noob"

### ISSUE THREAD

**Issue by MadhanDevlpr** [xZAYEDx/ZAYED_Bio-Data-#1]
You aren't a noob anymore

**Comment by MadhanDevlpr** [comment]
hope you remove that

**Comment by xZAYEDx** [comment]
Thank you for the compliment. But why do you feel I am not a noob?

**Comment by MadhanDevlpr** [comment]
cause you accepted honestly as you're a """ noob """

**Comment by xZAYEDx** [comment]
To be honest Yes I feel so, cos there are a lot of good developers out there I am no where of their level yet.

**Comment by MadhanDevlpr** [comment]
THe only way to be a good developer is to believe that you're not a  noob anymore
